# This file controls which features from the `ops-bot` repository below are enabled.
# - https://github.com/rapidsai/ops-bot

auto_merger: true
branch_checker: false
label_checker: true
release_drafter: false
recently_updated: true
forward_merger: true
