version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

# PIP_NO_DEPS="True" and PIP_NO_BUILD_ISOLATION="True" are set in the readthedocs build environment.
# Al of the project's build dependencies need to be provided via the conda environment
# at conda/environments/builddocs.yml.
# ref: https://docs.readthedocs.io/en/stable/guides/environment-variables.html
python:
  install:
    - method: pip
      path: .

conda:
  environment: conda/environments/builddocs.yml

sphinx:
  configuration: docs/source/conf.py
