version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_create_environment:
      - pip install .

conda:
  environment: conda/environments/builddocs.yml

sphinx:
  configuration: docs/source/conf.py
