version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_checkout:
      - bash ci/build_docs_pre_install.sh

conda:
  environment: conda/environments/builddocs.yml

sphinx:
  configuration: docs/source/conf.py
