version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  post_create_environment:
    - pip install -C rapidsai.disable-cuda=true -C rapidsai.matrix-entry="cuda-12.2" .

conda:
  environment: conda/environments/builddocs.yml

sphinx:
  configuration: docs/source/conf.py
