version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_create_environment:
      # explicitly passing matrix-entry so that 'libucx' is pulled in,
      # and therefore tested in this no-CUDA environment
      - |
        pip install \
          -C rapidsai.matrix-entry="cuda=12.2;cuda_suffixed=true" \
          .

conda:
  environment: conda/environments/builddocs.yml

sphinx:
  configuration: docs/source/conf.py
