version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

python:
  install:
    - method: pip
      path: .

conda:
  environment: conda/environments/builddocs.yml

sphinx:
  configuration: docs/source/conf.py
