version: 2

build:
  image: latest
  apt_packages:
    - libnuma1

python:
  version: 3.8
  install:
    - method: setuptools
      path: .

conda:
  environment: conda/environments/builddocs_py38.yml

sphinx:
  configuration: docs/source/conf.py
