version: 2

build:
  image: latest

python:
  version: 3.7
  install:
    - method: setuptools
      path: .

conda:
  environment: conda/environments/builddocs_py37.yml

sphinx:
  configuration: docs/source/conf.py
