c_compiler_version:
  - 13  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - 11  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
cxx_compiler_version:
  - 13  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - 11  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

ucx:
  - "==1.15.*"
