# Copyright (c) 2019-2023, NVIDIA CORPORATION.

{% set data = load_file_data("pyproject.toml") %}

{% set version = environ['RAPIDS_PACKAGE_VERSION'].strip('"').lstrip('v') %}
{% set py_version = environ['CONDA_PY'] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: ucx-py
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - ucx
    {% for r in data.get("build-system", {}).get("requires", []) %}
    - {{ r }}
    {% endfor %}
  run:
    - python
    {% for r in data.get("project", {}).get("dependencies", []) %}
    - {{ r }}
    {% endfor %}

test:
  imports:
    - ucp

about:
  home: {{ data.get("project", {}).get("urls", {}).get("Homepage", "") }}
  license: {{ data.get("project", {}).get("license", {}).get("text", "") }}
  license_file:
    {% for e in data.get("tool", {}).get("setuptools", {}).get("license-files", []) %}
    - ../../../{{ e }}
    {% endfor %}
  summary: {{ data.get("project", {}).get("description", "") }}
  dev_url: {{ data.get("project", {}).get("urls", {}).get("Source", "") }}
  doc_url: {{ data.get("project", {}).get("urls", {}).get("Documentation", "") }}
