{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set py_version = environ['CONDA_PY'] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}

package:
  name: ucx-py
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - cython
    - pip
    - python
    - tomli  # [py<311]
    - ucx
    - versioneer >=0.24
  run:
    - numpy
    - python
    - ucx
  run_constrained:
    - pynvml {{ pynvml }}

test:
  requires:
    - cudatoolkit {{ cuda_version }}.*
  imports:
    - ucp

about:
  home: http://rapids.ai/
  license: BSD-3-Clause
  license_family: BSD
  license_file: ../../../LICENSE
  summary: Python bindings for UCX
  dev_url: https://github.com/rapidsai/ucx-py
  doc_url: https://ucx-py.readthedocs.io
