# Copyright (c) 2019-2023, NVIDIA CORPORATION.

{% set data = load_file_data("pyproject.toml") %}

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') %}
{% set py_version = environ['CONDA_PY'] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: ucx-py
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script:
    - {{ PYTHON }} -m pip install --config-settings rapidsai.disable-cuda=true . -vv
  ignore_run_exports_from:
    - ucx

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - ucx
    {% for b_r in data["build-system"]["requires"] %}
    - {{ b_r }}
    {% endfor %}
    # 'libucx' wheel dependency is unnecessary... the 'ucx' conda-forge package is used here instead
    {% for rbb_r in data["tool"]["rapids-build-backend"]["requires"] if not rbb_r.startswith("libucx") %}
    - {{ rbb_r }}
    {% endfor %}
  run:
    - python
    - ucx >=1.15.0,<1.16.0
    # 'libucx' wheel dependency is unnecessary... the 'ucx' conda-forge package is used here instead
    {% for r in data["project"]["dependencies"] if not r.startswith("libucx") %}
    - {{ r }}
    {% endfor %}

test:
  imports:
    - ucp

about:
  home: {{ data["project"]["urls"]["Homepage"] }}
  license: {{ data["project"]["license"]["text"] }}
  license_file:
    {% for e in data["tool"]["setuptools"]["license-files"] %}
    - ../../../{{ e }}
    {% endfor %}
  summary: {{ data["project"]["description"] }}
  dev_url: {{ data["project"]["urls"]["Source"] }}
  doc_url: {{ data["project"]["urls"]["Documentation"] }}
