# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: ucx-py
  version: ${{ version }}

source:
  path: ../../..

build:
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  dynamic_linking:
    overlinking_behavior: "error"
  script:
    content: |
      python -m pip install --config-settings rapidsai.disable-cuda=true . -vv
requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
  host:
    - cython>=3.0.0
    - pip
    - python =${{ py_version }}
    - rapids-build-backend>=0.3.1,<0.4.0dev0
    - setuptools>=64.0.0
    - ucx
  run:
    - numpy>=1.23,<3.0a0
    - pynvml>=12.0.0,<13.0.0a0
    - python
    - ucx >=1.15.0,<1.19.0
  ignore_run_exports:
    by_name:
      - ucx


tests:
  - python:
      imports:
        - ucp
      pip_check: false


about:
  homepage: ${{ load_from_file("pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
