channels:
  - rapidsai
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - cuda-version=12.5
  - setuptools
  - cython>=3.0.0
  - pytest
  - pytest-asyncio
  - dask
  - distributed
  - cupy
  - numba>=0.57
  - rmm
