name: Update readthedocs branch

on:
  push:
    branches: ["branch-0.20"]

jobs:
  update:
    name: Update readthedocs branch
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout readthedocs
        uses: actions/checkout@v2.3.4
        with:
          ref: readthedocs
          fetch-depth: 0
      - name: Merge upstream changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          git fetch origin
          git merge origin/branch-0.20
          git push
