name: ucx-py wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'

jobs:
  ucx-py-wheel:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@feat/wheel-ci-actions-2
    with:
      package-name: ucx-py
      package-dir: .
      python-version: "3.8 3.9"
      gpu-smoketest: "import ucp; print(ucp.get_config())"
    secrets: inherit
