name: ucx-py wheels

on: [push]

jobs:
  ucx-py-wheel:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@feat/wheel-ci-actions-ptaylor
    with:
      package-name: ucx_py
      package-dir: .
      python-version: "3.8 3.9"
    secrets: inherit
